### ISSUE TITLE
Change CSV separator to comma

### ISSUE THREAD

**Issue by sNeAkingEoN** [dh-trier/musicovers#7]
Als Trennzeichen in CSV-Datei Komma statt Semikolon verwenden, damit Github das hübscher findet

**Comment by christofs** [comment]
Ja. Wichtig dabei ist, dass es wirklich überall umgestellt wird, beim Schreiben, aber auch beim Lesen von CSV-Dateien, damit alles weiter funktioniert.

**Comment by alueschow** [comment]
Scheint jetzt alles korrekt zu sein. Wenn Fehler auffallen, hier kurz melden.
