### ISSUE TITLE
Dokumentations-Datei: Informationen aus docstring nehmen

### ISSUE THREAD

**Issue by christofs** [dh-trier/musicovers#8]
Jeweils nicht wie derzeit den String "operations" aus der Funktion "write_docfile" verwenden, sondern den allgemeinen Text zum Skript, also den Anfang des "docstring". Da dieser relativ lang sein und mehrere Zeilen umfassen kann, muss das beim Aneinanderhängen auch der vorigen docstring-Teile bei der Formatierung irgendwie berücksichtigt werden, damit es lesbar und übersichtlich bleibt.

**Comment by alueschow** [comment]
Die Funktionen zum Lesen vorheriger Dokumentationsdateien und zum Schreiben der neuen Dok.-Datei sind jetzt in ein separates Modul ausgelagert, in dem diese Problematik auch berücksichtigt ist.
